rubyTmpDir: /usr/local/src
rubyUrl: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.gz
rubyCompressedFile: ruby-2.2.2.tar.gz
rubyName: ruby-2.2.2
tmpRubyPath: "{{rubyTmpDir}}/{{rubyName}}"
deploy_directory: /var/www
elasticsearch_version: 1.6
rvm1_rubies:
  - 'ruby-2.1.6'
  # - 'ruby-2.2.2'
redis_version: 3.0.2
admin_email: developer@example.com

logrotate_scripts:
  - name: rails
    path: /var/www/apps/*/shared/log/*.log
    options:
      - daily
      - missingok
      - compress
      - delaycompress
      - copytruncate
      - rotate 14
      - su deploy deploy
  - name: nginx
    path: /var/log/nginx/*.log
    options:
      - weekly
      - missingok
      - compress
      - delaycompress
      - notifempty
      - create 0640 www-date adm
      - rotate 8
    scripts:
      prerotate: "if [ -d /etc/logrotate.d/httpd-prerotate ]; then  run-parts /etc/logrotate.d/httpd-prerotate;  fi "
      postrotate: "invoke-rc.d nginx rotate >/dev/null 2>&1"
  - name: clamav-logs
    path: /var/log/clamav/*.gz
    options:
      - rotate 30
      - missingok
      - notifempty
      - daily
