rubyTmpDir: /usr/local/src
rubyUrl: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.gz
rubyCompressedFile: ruby-2.2.2.tar.gz
rubyName: ruby-2.2.2
tmpRubyPath: "{{rubyTmpDir}}/{{rubyName}}"
deploy_directory: /var/www
elasticsearch_version: 1.6
rvm1_rubies:
  - 'ruby-2.1.6'
  # - 'ruby-2.2.2'
