---

- hosts: web
  sudo: yes
  gather_facts: yes
  remote_user: ubuntu
  vars_files:
    - group_vars/web.yml
    - group_vars/database.yml
  vars:
    - redis_bind: 127.0.0.1
    - redis_version: 3.0.2

  vars_prompt:
    - name: 'postgres_user_password'
      prompt: 'Enter postgres user password'

  roles:
    - { role: rvm_io.rvm1-ruby, sudo: True }
    - common
    - web
    - database
    - DavidWittman.redis
