---

- hosts: web
  sudo: yes
  gather_facts: yes
  remote_user: ubuntu
  vars_files:
    - group_vars/web.yml
    - group_vars/database.yml

  roles:
    - { role: rvm_io.rvm1-ruby, sudo: True }
    - common
    - web
    - database
