- name: Create deployment user
  user: name=deploy comment="Application deployment user" generate_ssh_key=yes shell=/bin/bash

- authorized_key: user=deploy key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Add users to Deploy group
  user: name={{item}} groups=deploy append=yes
  with_items:
    - ubuntu

- name: Create deployment directory
  file: path={{deploy_directory}} owner=deploy group=deploy state=directory

- name: Make shared directories
  file: path={{deploy_directory}}/{{item}} group=deploy owner=deploy state=directory
  with_items:
    - conf
    - vendor
    - apps
    - assets
    - ssl
    - conf/sites-available
    - conf/sites-enabled

- name: Allow deploy user to sudo nginx without password
  copy: src=etc_sudoers.d_1_deploy dest=/etc/sudoers.d/1_deploy mode=0440
