- name: Install Elasticsearch apt key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Add Elasticsearch apt repo
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/{{ elasticsearch_version }}/debian stable main' state=present update_cache=yes

- name: Install Elasticsearch
  apt: pkg=elasticsearch state=present
  notify:
    - enable and start Elasticsearch
