- name: Install security-related packages
  apt: pkg={{ item }} state=present
  with_items:
    - fail2ban

- name: Copy fail2ban configuration into place
  template: src=etc_fail2ban_jail.local.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban
