- name: Install Phusion Passenger apt key
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7

- name: Install prerequisites for Phusion repo
  apt: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Phusion apt repo
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main' state=present update_cache=yes

- name: Install Nginx and Passenger
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - nginx-extras
    - passenger
  notify:
    - restart nginx

- name: Remove the default app
  command: rm -rf /etc/nginx/sites-enabled/default

- name: Copy nginx.conf
  template: src=etc_nginx_nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
