- name: Install production dependencies
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - libpq-dev
    - postgresql-client
    - redis-server
    - imagemagick
    - git-core


- include: wkhtmltopdf.yml tags: wkhtmltopdf
