- name: Create the wkhtmltopdf app directory.
  file: state=directory path=/opt/wkhtmltopdf

- name: Fetching wkhtmltopdf archive
  get_url: url=http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb dest=/opt/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb validate_certs=no

- name: Install wkthtmltopdf package
  apt: deb=/opt/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb state=installed
