---
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=1800

  - name: Upgrade all packages safely
    apt: upgrade=safe

  - name: Install helpful packages and pre reqs
    apt: pkg={{ item }} state=present
    with_items:
      - sudo
      - vim
      - mtr-tiny
      - git
      - ntp
      - build-essential
      - language-pack-en
      - htop

  - name: Configure NTP
    copy: src=etc_ntp.conf dest=/etc/ntp.conf backup=yes
    notify:
      - restart ntp

  - name: Configure sshd
    copy: src=etc_ssh_sshd_config dest=/etc/ssh/sshd_config backup=yes
    notify:
      - restart ssh

  - include: clamav.yml tags=clamav
